name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise run check

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - name: Coverage
        uses: ncruces/go-coverage-report@main
      - name: Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
